### ISSUE TITLE
Bug: cache use problem with build_only layers single `--layer-type`

### ISSUE THREAD

**Issue by smoser** [project-stacker/stacker#442]
### stacker version

v1.0.0-rc4-8e267fc

### Describe the bug

When using `build_only: true` for as under-layers stacker can fail to setup a valid container.

The following comment string in the beginning of lxcRootfsString in pkg/overlay/metadata.go [here](https://github.com/project-stacker/stacker/blob/8e267fc269f987a7dcb38a117b9efe8780c81d2e/pkg/overlay/metadata.go#L97) is not correct for all use cases:
>    // find *any* manifest to mount: we don't care if this is tar or
>    // squashfs, we just need to mount something. the code that generates
>    // the output needs to care about this, not this code.
>    //
>    // if there are no manifests (this came from a tar layer or whatever),
>    // that's fine too; we just end up with two workaround directories as
>    // below

lxcRootfsString will ovl.Manifests dictionary and pick the first manifest it finds.  In the case where stacker is only building squashfs a stacker file like below will fail if the dictionary traversal does not select 'squash+true' first.

```yaml
minbase:
  build_only: true
  from:
    type: docker
    url: docker://busybox:latest
  run: |
    echo hello > /minbase.txt

rootfs:
  from:
    type: built
    tag: minbase
  run: |
    [ -e /minbase.txt ]
```

The problem can be seen when reading the serialized overlay_metadata.json in roots/minbase/overlay_metadata.json the 'tar+false' entry is missing a layer (it has only 1, where the squashfs+true entry has 2). The file below is trimmed.

```yaml
{
    "Manifests": {
        "squashfs+true": {
            "schemaVersion": 2,  
            "config": {
                "mediaType": "application/vnd.oci.image.config.v1+json",
                "digest": "sha256:6f915f8915d71fb46c2982fcaf97ae40dae01bb57b7ec257eaa3c821cd1688dc",
                "size": 576
            },
            "layers": [
                {
                    "mediaType": "application/vnd.stacker.image.layer.squashfs+zstd+verity",
                    "digest": "sha256:243c9d7f13852c8cdf10afa68f4ffc77bb59b7ef212b553f215c9531bf4828
80",                
                    "size": 2301952,
                    }
                },  
                {
                    "mediaType": "application/vnd.stacker.image.layer.squashfs+zstd+verity",
                    "digest": "sha256:ad18d87c6d5abc32dbd385daa1046527838d3ebf4f6dc9e5e0c0501a582802
52",                
                    "size": 8192,
                }
            ]
        },
        "tar+false": {
            "schemaVersion": 2,
            "config": {
                "mediaType": "application/vnd.oci.image.config.v1+json",
                "digest": "sha256:3488e6e2e41e62fc51be840cd61d806d5b45defdb84a2e6c99ea8a0edb4b6cc7",
                "size": 575
            },
            "layers": [
                {   
                    "mediaType": "application/vnd.oci.image.layer.v1.tar+gzip",
                    "digest": "sha256:1487bff95222881565c7c063129c2c2ce3d6fc4d14796ac7627bd1f167bc5621",                
                    "size": 2592227
                }
            ]
        }
    },
...
```

### To reproduce

The attached [recreate.sh](https://github.com/project-stacker/stacker/files/10969448/recreate.sh.txt) will reproduce the bug.

It reads the following environment variables:
 * RUNS: default=50 number of runs
 * BUILD_ONLY: default=true - allowed values ('true', 'false')
 * LAYER_TYPES: default=squashfs - allowed values ('squashfs', 'tar', 'squashfs,tar', 'tar,squashfs')

Changing the value of BUILD_ONLY to 'false'  or LAYER_TYPES  to 'squashfs,tar' (or 'tar,squashfs') will cause the issue to not reproduce.

The problem only occurs with stacker files that have 'build_only: true' and are built '--layer-type=squashfs'.

**Comment by smoser** [comment]
Just for ease of viewing, i'll  describe what 'recreate.sh' does.
It basically just loops over a build of the following `stacker.yaml` defining NUMBER each time so that 'rootfs' is forced to be built.

It may be relevant that 'docker://busybox:latest' is initially a tar layer that gets converted to squashfs by stacker.

stacker.yaml:
```yaml
minbase:
  build_only: true
  from:
    type: docker
    url: docker://busybox:latest
  run: |
    echo hello > /minbase.txt

rootfs:
  from:
    type: built
    tag: minbase
  run: |
    n=${{NUMBER}}
    [ -e /minbase.txt ] && echo "run $n good" ||
        { echo "run $n bad"; exit 1; }
```

And then:
```bash
n=0
while [ $n -lt 50 ] && n=$((n+1)); do
    stacker build --substitute=NUMBER=$n || exit
done
```

**Comment by smoser** [comment]
@hallyn , did you think is fixed by #454 ?
if so, can we validate that and close?

**Comment by hallyn** [comment]
It doesn't fix it.  It fails after a random number of iterations - my last attempt hit 

```
+ echo 'run 23 bad'
run 23 bad
```

**Comment by hallyn** [comment]
https://pastebin.com/PM24dtr4   shows the backtrace.

**Comment by hallyn** [comment]
Perhaps this failure is due to using fuse for atomfs without the mount-is-ready notification channel.

**Comment by smoser** [comment]
> Perhaps this failure is due to using fuse for atomfs without the mount-is-ready notification channel.

its not. it is golang dict ordering.
